import React, { useState, useEffect } from 'react';
import { StudyContextType } from '../types';
import { generateFlashcards } from '../services/geminiService.ts';
import { Loader2, Plus, RefreshCw, CheckCircle2, ChevronLeft, ChevronRight, RotateCw, Sparkles, AlertCircle, X, Download } from 'lucide-react';
import { jsPDF } from "jspdf";

interface FlashcardsProps {
  context: StudyContextType;
}

const Flashcards: React.FC<FlashcardsProps> = ({ context }) => {
  const { documents, notes, flashcards, setFlashcards } = context;
  const [isLoading, setIsLoading] = useState(false);
  const [currentIndex, setCurrentIndex] = useState(0);
  const [isFlipped, setIsFlipped] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const handleGenerate = async () => {
    if (documents.length === 0 && !notes) {
        setError("Please upload documents in Study Lab first.");
        return;
    }

    setIsLoading(true);
    setError(null);
    try {
        // Append to existing if any, or create new
        const newCards = await generateFlashcards(documents, notes, flashcards.length);
        setFlashcards([...flashcards, ...newCards]);
    } catch (err: any) {
        console.error(err);
        setError(err.message || "Error generating cards. Please try again.");
    } finally {
        setIsLoading(false);
    }
  };

  const handleDownloadPDF = () => {
      if (flashcards.length === 0) return;

      // Initialize jsPDF (default is mm, a4)
      const doc = new jsPDF();
      
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 20;
      const cardWidth = pageWidth - (margin * 2);
      const minCardHeight = 40; // Minimum height
      
      // Title
      doc.setFontSize(22);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(79, 70, 229); // Primary color
      doc.text("Flashcards", margin, 20);
      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100, 100, 100);
      doc.text(`Generated by ScholarAI - ${new Date().toLocaleDateString()}`, margin, 28);

      let yPos = 35; 

      flashcards.forEach((card, index) => {
          // Layout Config
          const splitRatio = 0.35; // 35% for Question, 65% for Answer
          const qWidth = (cardWidth * splitRatio) - 8;
          const aWidth = (cardWidth * (1 - splitRatio)) - 8;
          const fontSize = 11;
          const lineHeight = 5;

          doc.setFontSize(fontSize);
          doc.setFont("helvetica", "bold");
          const qLines = doc.splitTextToSize(card.question, qWidth);
          
          doc.setFont("helvetica", "normal");
          const aLines = doc.splitTextToSize(card.answer, aWidth);

          // Calculate Dynamic Height
          const textHeight = Math.max(qLines.length, aLines.length) * lineHeight;
          const cardHeight = Math.max(minCardHeight, textHeight + 20); // Add padding

          // Check Page Break
          if (yPos + cardHeight > pageHeight - margin) {
              doc.addPage();
              yPos = 20;
          }

          // Draw Card Box
          doc.setDrawColor(203, 213, 225); // Slate 300
          doc.setFillColor(248, 250, 252); // Slate 50
          doc.roundedRect(margin, yPos, cardWidth, cardHeight, 3, 3, 'FD');

          // Divider Line
          const splitX = margin + (cardWidth * splitRatio);
          doc.setDrawColor(226, 232, 240); // Slate 200
          doc.line(splitX, yPos, splitX, yPos + cardHeight);

          // Render Question
          doc.setFont("helvetica", "bold");
          doc.setTextColor(79, 70, 229); // Primary
          doc.text(`Q${index + 1}`, margin + 4, yPos + 10);
          
          doc.setTextColor(30, 41, 59); // Slate 800
          doc.text(qLines, margin + 4, yPos + 18);

          // Render Answer
          doc.setFont("helvetica", "bold");
          doc.setTextColor(100, 116, 139); // Slate 500
          doc.text("Answer", splitX + 4, yPos + 10);

          doc.setFont("helvetica", "normal");
          doc.setTextColor(51, 65, 85); // Slate 700
          doc.text(aLines, splitX + 4, yPos + 18);

          yPos += cardHeight + 8; // Gap between cards
      });

      doc.save("ScholarAI_Flashcards.pdf");
  };

  const handleNext = () => {
    setIsFlipped(false);
    setTimeout(() => {
        setCurrentIndex((prev) => (prev + 1) % flashcards.length);
    }, 200);
  };

  const handlePrev = () => {
    setIsFlipped(false);
    setTimeout(() => {
        setCurrentIndex((prev) => (prev - 1 + flashcards.length) % flashcards.length);
    }, 200);
  };

  const toggleLearned = (e: React.MouseEvent) => {
    e.stopPropagation(); // Prevent card flip
    const updated = [...flashcards];
    updated[currentIndex].isLearned = !updated[currentIndex].isLearned;
    setFlashcards(updated);
  };

  // Keyboard navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
        if (flashcards.length === 0) return;
        if (e.key === 'ArrowRight') handleNext();
        if (e.key === 'ArrowLeft') handlePrev();
        if (e.key === ' ' || e.key === 'Enter') setIsFlipped(prev => !prev);
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [flashcards]); 

  if (flashcards.length === 0) {
      return (
          <div className="flex flex-col items-center justify-center min-h-[60vh] text-center p-8 animate-fade-in relative glass-panel rounded-3xl mx-auto max-w-2xl mt-10">
              <div className="bg-primary-50/80 dark:bg-primary-900/50 p-6 md:p-8 rounded-full text-primary-600 dark:text-primary-400 mb-6 shadow-sm backdrop-blur-sm">
                  <RefreshCw size={48} className="md:w-16 md:h-16" />
              </div>
              <h2 className="text-2xl md:text-3xl font-bold text-slate-800 dark:text-slate-100 mb-3">No Flashcards Yet</h2>
              <p className="text-slate-500 dark:text-slate-400 max-w-md mb-8 text-base md:text-lg leading-relaxed">
                  Generate flashcards from your notes to start practicing key concepts and definitions.
              </p>
              
              {error && (
                <div className="w-full max-w-md bg-red-50/80 dark:bg-red-900/30 border border-red-100 dark:border-red-900/50 rounded-xl p-4 flex items-start gap-3 mb-6 text-red-700 dark:text-red-300 text-left">
                    <AlertCircle className="shrink-0 mt-0.5" size={20} />
                    <div className="flex-1">
                        <p className="font-semibold text-sm">Error</p>
                        <p className="text-xs mt-1 opacity-90">{error}</p>
                    </div>
                    <button onClick={() => setError(null)} className="text-red-400 hover:text-red-700 dark:hover:text-red-200 transition-colors">
                        <X size={18} />
                    </button>
                </div>
              )}
              
              <button 
                onClick={handleGenerate}
                disabled={isLoading}
                className="bg-primary-600/90 hover:bg-primary-700/90 backdrop-blur-sm text-white px-8 py-4 rounded-xl font-bold shadow-lg shadow-primary-500/20 transition-all flex items-center gap-3 hover:-translate-y-1 disabled:opacity-70 disabled:hover:translate-y-0 border border-white/20"
              >
                {isLoading ? <Loader2 className="animate-spin" /> : <Sparkles />}
                {isLoading ? "Generating Cards..." : "Generate AI Flashcards"}
              </button>
              
              {(documents.length === 0 && !notes) && (
                  <p className="mt-6 text-sm text-amber-600 dark:text-amber-400 bg-amber-50/80 dark:bg-amber-900/20 px-4 py-2 rounded-lg border border-amber-100 dark:border-amber-900/30 flex items-center gap-2 backdrop-blur-sm">
                      <span className="font-bold">Pro Tip:</span> You need to upload content in Study Lab first.
                  </p>
              )}
          </div>
      );
  }

  const currentCard = flashcards[currentIndex];

  return (
    <div className="max-w-4xl mx-auto space-y-6 md:space-y-8 pb-8">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
            <h2 className="text-2xl md:text-3xl font-bold text-slate-800 dark:text-slate-100 tracking-tight">Flashcards</h2>
            <div className="flex items-center gap-2 mt-1">
                <span className="text-sm font-medium text-slate-500 dark:text-slate-400 bg-white/50 dark:bg-slate-800/50 border border-white/50 dark:border-white/10 px-2 py-0.5 rounded text-xs">
                    Card {currentIndex + 1} of {flashcards.length}
                </span>
                {currentCard.isLearned && (
                    <span className="text-xs font-bold text-green-600 dark:text-green-400 bg-green-50/80 dark:bg-green-900/30 border border-green-100/50 px-2 py-0.5 rounded flex items-center gap-1 backdrop-blur-sm">
                        <CheckCircle2 size={12} /> Learned
                    </span>
                )}
            </div>
        </div>
        <div className="flex items-center gap-2 self-start sm:self-auto">
            <button 
                onClick={handleDownloadPDF}
                className="flex items-center gap-2 text-slate-600 dark:text-slate-300 font-bold text-sm bg-white/50 dark:bg-slate-800/50 border border-white/50 dark:border-white/10 px-4 py-2 rounded-lg hover:bg-white/80 dark:hover:bg-slate-700/80 transition-colors shadow-sm"
            >
                <Download size={16} />
                Download PDF
            </button>
            <button 
                onClick={handleGenerate} 
                disabled={isLoading}
                className="flex items-center gap-2 text-primary-600 dark:text-primary-400 font-bold text-sm bg-primary-50/80 dark:bg-primary-900/30 border border-primary-100/50 dark:border-primary-800/50 px-4 py-2 rounded-lg hover:bg-primary-100/80 dark:hover:bg-primary-900/50 transition-colors disabled:opacity-50"
            >
                {isLoading ? <Loader2 size={16} className="animate-spin" /> : <Plus size={16} />}
                Add More
            </button>
        </div>
      </div>

      {error && (
        <div className="bg-red-50/80 dark:bg-red-900/30 border border-red-100 dark:border-red-900/50 rounded-xl p-4 flex items-start gap-3 text-red-700 dark:text-red-300 animate-fade-in glass-panel">
            <AlertCircle className="shrink-0 mt-0.5" size={20} />
            <div className="flex-1">
                <p className="font-semibold text-sm">Failed to generate more cards</p>
                <p className="text-xs mt-1 opacity-90">{error}</p>
            </div>
            <button onClick={() => setError(null)} className="text-red-400 hover:text-red-700 dark:hover:text-red-200 transition-colors">
                <X size={18} />
            </button>
        </div>
      )}

      {/* Card Container */}
      <div className="flex flex-col items-center">
        {/* The Card */}
        <div className="relative w-full aspect-[3/2] max-h-[400px] perspective-1000 group cursor-pointer mb-6" onClick={() => setIsFlipped(!isFlipped)}>
            <div className={`flip-card w-full h-full duration-500 preserve-3d ${isFlipped ? 'flipped' : ''}`}>
                <div className="flip-card-inner w-full h-full relative transition-transform duration-500" style={{ transformStyle: 'preserve-3d', transform: isFlipped ? 'rotateY(180deg)' : '' }}>
                    {/* Front */}
                    <div className="flip-card-front absolute w-full h-full backface-hidden glass-card bg-white/80 dark:bg-slate-800/80 rounded-3xl shadow-xl shadow-slate-200/40 dark:shadow-slate-900/40 p-8 md:p-12 flex flex-col items-center justify-center text-center border-2 border-white/50 dark:border-white/5">
                        <div className="absolute top-6 left-6 flex items-center gap-2">
                            <div className="w-2 h-2 rounded-full bg-indigo-400"></div>
                            <span className="text-xs font-bold tracking-widest text-slate-400 uppercase">Question</span>
                        </div>
                        
                        <div className="w-full max-h-[80%] overflow-y-auto custom-scrollbar px-2 flex items-center justify-center">
                            <h3 className="text-xl md:text-3xl font-bold text-slate-800 dark:text-slate-100 leading-snug">{currentCard.question}</h3>
                        </div>
                        
                        <div className="absolute bottom-6 w-full flex flex-col items-center gap-2 text-slate-400 text-sm">
                            <span className="flex items-center gap-2 bg-slate-100/50 dark:bg-slate-700/50 px-3 py-1 rounded-full text-xs font-medium">
                                <RotateCw size={12} /> Tap to flip
                            </span>
                        </div>
                    </div>

                    {/* Back */}
                    <div className="flip-card-back absolute w-full h-full backface-hidden bg-slate-900/95 dark:bg-slate-950/95 backdrop-blur-xl rounded-3xl shadow-xl shadow-slate-900/20 p-8 md:p-12 flex flex-col items-center justify-center text-center text-white border border-white/10" style={{ transform: 'rotateY(180deg)' }}>
                        <div className="absolute top-6 left-6 flex items-center gap-2">
                            <div className="w-2 h-2 rounded-full bg-emerald-400"></div>
                            <span className="text-xs font-bold tracking-widest text-slate-500 uppercase">Answer</span>
                        </div>
                        
                        <div className="w-full max-h-[85%] overflow-y-auto custom-scrollbar px-2 flex items-center justify-center">
                            <p className="text-lg md:text-xl leading-relaxed font-medium text-slate-100">{currentCard.answer}</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        {/* Action Bar */}
        <div className="w-full flex items-center justify-between gap-4 max-w-lg bg-white/40 dark:bg-slate-800/40 backdrop-blur-md p-2 rounded-2xl border border-white/40 dark:border-white/10 shadow-sm">
            <button 
                onClick={handlePrev} 
                className="w-12 h-12 rounded-xl bg-white dark:bg-slate-700 text-slate-600 dark:text-slate-200 hover:text-primary-600 dark:hover:text-primary-400 hover:bg-primary-50 dark:hover:bg-primary-900/30 flex items-center justify-center transition-all shadow-sm active:scale-95"
                title="Previous Card"
            >
                <ChevronLeft size={24} />
            </button>

            <button 
                onClick={toggleLearned}
                className={`
                    flex-1 flex items-center justify-center gap-2 h-12 rounded-xl font-bold text-sm transition-all shadow-sm
                    ${currentCard.isLearned 
                        ? 'bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400 border border-green-200 dark:border-green-800' 
                        : 'bg-white dark:bg-slate-700 text-slate-500 dark:text-slate-300 border border-transparent hover:border-green-200 hover:text-green-600 hover:bg-green-50 dark:hover:bg-green-900/20'
                    }
                `}
            >
                <CheckCircle2 size={18} />
                {currentCard.isLearned ? 'Mastered' : 'Mark as Learned'}
            </button>

            <button 
                onClick={handleNext} 
                className="w-12 h-12 rounded-xl bg-white dark:bg-slate-700 text-slate-600 dark:text-slate-200 hover:text-primary-600 dark:hover:text-primary-400 hover:bg-primary-50 dark:hover:bg-primary-900/30 flex items-center justify-center transition-all shadow-sm active:scale-95"
                title="Next Card"
            >
                <ChevronRight size={24} />
            </button>
        </div>
      </div>
    </div>
  );
};

export default Flashcards;
